use channel over github api
FuelLabs/fuelup pull request #104
Opened 2022-07-15 01:36 UTC by bingcicle

Closes #87 

_WIP_

2022-07-19 04:42 UTC, bingcicle commented
This should be ready to review despite `fuelup-init` test failing (this is expected since #103 is merged). I think after this PR is ready and merged, we should cut a new release and that should publish a new version without `v` prefix and the CI will work as intended.

2022-07-20 23:58 UTC, JoshuaBatty submitted a review, later dismissed
Nice work looks good, I'll approve but might want to get one more tick before merging.

2022-07-21 08:08 UTC, mitchmindtree requested changes
Looking good! Just a small things.

> Currently we do not check the hash when we download the file but this can be done in a future PR.

Maybe we should open an issue for this to make sure we don't forget?

2022-07-22 00:47 UTC, bingcicle commented
>  Maybe we should open an issue for this to make sure we don't forget?

I have a separate PR open at #108 for this that merges into this branch - wanted to keep separation of concerns since they weren't exactly doing the same thing

2022-07-22 05:04 UTC, bingcicle commented
Hmm, I actually discovered a toml parsing bug as a result of #100. I have included the fix in this PR because it was only a one-liner fix (in this commit [1ac5155](https://github.com/FuelLabs/fuelup/pull/104/commits/1ac5155a310f0725406dc82a787db7336431377c))

It has to do with how reading the string actually read the unescaped quotation marks as well because I didn't unwrap the value using `.value()`.

2022-07-25 05:05 UTC, mitchmindtree reviewed
Getting closer! Just a few more nits.

> Hmm, I actually discovered a toml parsing bug as a result of https://github.com/FuelLabs/fuelup/pull/100. I have included the fix in this PR because it was only a one-liner fix (in this commit [1ac5155](https://github.com/FuelLabs/fuelup/pull/104/commits/1ac5155a310f0725406dc82a787db7336431377c))

Looking a bit closer at the `Settings` type, it seems to be doing some manual parsing that might also be better replaced by deriving `Deserialize`? Probably best addressed in a separate PR either way.

2022-07-25 06:28 UTC, bingcicle commented on src/config.rs
> +                        && e.file_name().to_string_lossy().starts_with("latest")
Right, yes - I did indeed define a `pub const toolchain` within `fuelup_toolchain.rs`!

2022-07-25 06:30 UTC, bingcicle commented
> Looking a bit closer at the `Settings` type, it seems to be doing some manual parsing that might also be better replaced by deriving `Deserialize`?

Good point - will create an issue for this

2022-07-25 23:32 UTC, JoshuaBatty submitted a review, later dismissed
LGTM, will defer to @mitchmindtree for final approval.

2022-07-28 03:43 UTC, mitchmindtree submitted a review, later dismissed
:ship:

2022-08-07 10:31 UTC, JoshuaBatty approved these changes

2022-08-08 00:55 UTC, merged