refactor: break up command.rs into files per subcommand
FuelLabs/fuelup pull request #349
Opened 2023-01-18 16:05 UTC by deekerno

Closes #342.

## Changelog
- Break up `command.rs` testing file into separate files organized by subcommand

2023-01-18 23:41 UTC, deekerno commented
@bingcicle How do you want me to resolve the lints? I could put some `#[allow(...)]` lints in places, but I want to make sure that I do what's right for the project.

2023-01-19 04:23 UTC, bingcicle commented
@deekerno First of all, thanks for the PR! :smile: 

It seems like declaring testcfg as public fixes the issue: https://github.com/rust-lang/rust/issues/46379#issuecomment-548787629. Not sure if there's a better way to go about this, but this looks like it will do for now!

2023-01-19 05:32 UTC, bingcicle requested changes

2023-01-19 05:32 UTC, bingcicle commented on tests/utils/mod.rs
> +use std::path::Path;
Hmm, I'm personally not really a fan of naming things `utils`, without enough care over time it feels like pieces of code that get hard to categorize turn into _utils_ and it just becomes a dumping ground of unrelated functions, perhaps we can name this something else? eg. `checks`, or `expects`

2023-01-20 16:25 UTC, bingcicle approved these changes
LGTM :tada: thanks for the PR!

2023-01-20 23:51 UTC, deekerno commented
@bingcicle Looks like it's failing on the same test that master is currently failing on. 🤔

2023-01-22 03:46 UTC, merged