Fix several typos
FuelLabs/fuelup pull request #534
Opened 2023-12-03 18:59 UTC by nnsW3

Hello there,
I managed to fix several minor typos found in your documentation, hope it helps.
Best regards, Elias.

2023-12-04 17:41 UTC, sdankel requested changes

2023-12-04 17:41 UTC, sdankel commented on docs/src/concepts/channels.md
> +> The `latest` channel is used to point latest compatible versions of `forc` and `fuel-core`, after version v0.20.0 latest is changed to point to the latest network. This is a breaking change and sho
It was correct before.

2023-12-04 17:41 UTC, sdankel commented on docs/src/developer_guide/contributing_to_fuelup.md
> +If you are planning something big, for example, related to multiple components or changes in current behaviors, make sure to open an issue to discuss with us before starting on the implementation.
```suggestion
If you are planning something big, for example, related to multiple components or changes to current behaviors, make sure to open an issue to discuss with us before starting on the implementation.
```

2023-12-04 17:41 UTC, sdankel commented on docs/src/developer_guide/contributing_to_fuelup.md
> +  - We may discuss the problem and solution to the issue.
Correct before

2023-12-04 20:13 UTC, nnsW3 commented
solved, hope it helps

2023-12-12 23:05 UTC, sdankel commented
You'll need to fix the conflicts with master.

2023-12-13 08:39 UTC, nnsW3 commented
done

2023-12-18 22:49 UTC, sdankel commented on docs/src/developer_guide/building_a_channel.md
> +There may be times when we need a channel for a one-off event eg. testnets. During these events, we do not
```suggestion
There may be times when we need a channel for a one-off event e.g. testnets. During these events, we do not
```

2023-12-18 22:50 UTC, sdankel approved these changes

2023-12-18 22:51 UTC, merged